
node {
    checkout([
        $class: 'GitSCM',
        branches: [[name: "*/${config.repoBranch}"]],
        userRemoteConfigs: [[
            url: config.repoUrl,
            credentialsId: config.repoCredId
        ]],
        extensions: [[
            $class: 'RelativeTargetDirectory',
            relativeTargetDir: 'apigw-pipeline'
        ]]
    ])
    loadProperties()
    deploy()
    summary()
}
