
node {
    checkout([
        $class: 'GitSCM',
        branches: [[name: '*/main']],
        userRemoteConfigs: [[
            url: 'https://github.com/ahmadhidayatt/asset-api-testcicd-v2',
            credentialsId: 'ahmadhidayatt'
        ]]
    ])
    loadProperties()
    deploy()
    summary()
}
